/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <unistd.h>  /* pour sleep() */

static int courante;

int *
add_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	
	printf ("[ADD] Début traitement - arg: %d\n", *argp);
	sleep(2);  /* Temporisation de 2 secondes */
	
	courante = courante + *argp;
	printf ("[ADD] Fin traitement - courante: %d\n", courante);
	result = courante;
	return &result;
}

int *
mul_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	
	printf ("[MUL] Début traitement - arg: %d\n", *argp);
	sleep(3);  /* Temporisation de 3 secondes */
	
	courante = courante * *argp;
	printf ("[MUL] Fin traitement - courante: %d\n", courante);
	result = courante;
	return &result;
}

void *
init_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;
	
	printf ("[INIT] Début initialisation - valeur: %d\n", *argp);
	sleep(1);  /* Temporisation de 1 seconde */
	
	courante = *argp;
	printf ("[INIT] Fin initialisation - courante: %d\n", courante);
	return (void *) &result;
}
