/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"
#include <stdio.h>
#include <unistd.h>

int memoire = 0;
int *currante = &memoire;

int *add_1_svc(tuple *argp, struct svc_req *rqstp)
{
    static int result;
    if (argp->mem){
    	printf("[ADD] Calcul: %d + %d\n", argp->a, *currante);
    	result = argp->a + *currante;
	} else {
		printf("[ADD] Calcul: %d + %d\n", argp->a, argp->b);
		result = argp->a + argp->b;
	}
	*currante = result;
    printf("[ADD] Résultat: %d\n", result);
    
    return &result;
}

int *mul_1_svc(tuple *argp, struct svc_req *rqstp)
{
    static int result;
    
    if (argp->mem){
		printf("[MUL] Calcul: %d * %d\n", argp->a, *currante);
		result = argp->a * *currante;
	} else {
		printf("[MUL] Calcul: %d * %d\n", argp->a, argp->b);
		result = argp->a * argp->b;
	}
	*currante = result;
	printf("[MUL] Résultat: %d\n", result);

    return &result;
}

int *init_1_svc(int *argp, struct svc_req *rqstp)
{
    static int result;
    
    printf("[INIT] currante = %d ", *argp);
    *currante = *argp;
    
    return &result;
}
