/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

int *
add_0_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	/* Simple example implementation: return arg + 1 */
	result = *argp + 1;

	return &result;
}

int *
mul_0_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	/* Simple example implementation: return arg * 2 */
	result = (*argp) * 2;

	return &result;
}

void *
init_0_svc(int *argp, struct svc_req *rqstp)
{
	static char result;
	/* Example: no meaningful result for init (xdr_void), return address */
	(void) argp; (void) rqstp;
	return (void *)&result;
}
